---
- hosts: localhost
  vars:
    AWS_REGION: "us-west-2"
    cluster: "marketplace-cache-staging"
    service: "marketplace-cache-staging"
    short_name: "marketplace-cache-staging"
    task_definition: "marketplace-cache:7"
  tasks:
  - name: get ecs service details
    ecs_service_facts:
      cluster: "{{ cluster }}"
      service: "{{ short_name }}"
      details: true
    register: ecs_service_facts_output
  - set_fact:
      loadbalancers: "{{ ecs_service_facts_output.services[0].loadBalancers }}"
    when: ecs_service_facts_output.services | count
  - name: create or update ecs service using target group
    ecs_service:
      state: present
      name: "{{ short_name }}"
      cluster: "{{ cluster }}"
      task_definition: "{{ task_definition }}"
      load_balancers: "{{ loadbalancers }}"
      desired_count: "{{ app_desired_count | default( 1 ) }}"
      deployment_configuration:
        minimum_healthy_percent: "{{ app_minimum_healthy | default( 100 ) }}"
        maximum_percent: "{{ app_maximum_percent | default( 200 )}}"
